import childProcess from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const GENERATED_NOTICE = "Generated by scripts/build_ko_ui_assets.mjs; do not edit.";
const DEFAULT_PIXEL_SIZE = 16;
const GUARDED_KINDS = new Set(["internal-token", "dynamic-user-content"]);
const TRANSLATED_KINDS = new Set(["fixed-ui-label", "fixed-ui-format", "diagnostic"]);

const scriptPath = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(scriptPath), "..");

const defaultConfig = {
  fontPath: path.join(repoRoot, "fonts", "dunggeunmo", "DungGeunMo.ttf"),
  stringsPath: path.join(repoRoot, "resources", "ko-ui", "strings.json"),
  outRoot: repoRoot,
  pixelSize: DEFAULT_PIXEL_SIZE,
};

class UsageError extends Error {
  constructor(message) {
    super(message);
    this.name = "UsageError";
  }
}

const usage = () => `Usage:
  node scripts/build_ko_ui_assets.mjs [--check] [--font <path>] [--strings <path>] [--out-dir <path>] [--pixel-size <n>]

Generates:
  js/ko-ui-strings.js
  js/ko-ui-font.js
  c/ko_ui_strings.h
  c/ko_ui_font.h`;

const parseArgs = (argv) => {
  const config = { ...defaultConfig, check: false };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    const readValue = () => {
      index += 1;
      if (index >= argv.length) throw new UsageError(`Missing value for ${arg}`);
      return argv[index];
    };

    if (arg === "--check") config.check = true;
    else if (arg === "--font") config.fontPath = path.resolve(readValue());
    else if (arg === "--strings") config.stringsPath = path.resolve(readValue());
    else if (arg === "--out-dir") config.outRoot = path.resolve(readValue());
    else if (arg === "--pixel-size") {
      const value = Number.parseInt(readValue(), 10);
      if (!Number.isInteger(value) || value < 8 || value > 64) {
        throw new UsageError("--pixel-size must be an integer from 8 to 64");
      }
      config.pixelSize = value;
    } else if (arg === "--help" || arg === "-h") {
      config.help = true;
    } else {
      throw new UsageError(`Unknown argument: ${arg}`);
    }
  }

  return config;
};

const slash = (filePath) => path.relative(repoRoot, filePath).replaceAll(path.sep, "/");
const sha256 = (value) => crypto.createHash("sha256").update(value).digest("hex");
const sha256File = (filePath) => sha256(fs.readFileSync(filePath));

const readJson = (filePath) => JSON.parse(fs.readFileSync(filePath, "utf8"));

const validateInventory = (inventory) => {
  const errors = [];
  const seenIds = new Set();

  if (!inventory || typeof inventory !== "object" || Array.isArray(inventory)) {
    return { errors: ["inventory root must be an object"], stringEntries: [], glyphChars: [] };
  }
  if (!Array.isArray(inventory.entries)) {
    return { errors: ["inventory entries must be an array"], stringEntries: [], glyphChars: [] };
  }

  const stringEntries = [];
  const glyphCodePoints = new Set();

  for (const [index, entry] of inventory.entries.entries()) {
    const label = entry && typeof entry === "object" && typeof entry.id === "string" ? entry.id : `entries[${index}]`;

    if (!entry || typeof entry !== "object" || Array.isArray(entry)) {
      errors.push(`${label}: entry must be an object`);
      continue;
    }
    if (typeof entry.id !== "string" || entry.id.length === 0) errors.push(`${label}: id is required`);
    else if (seenIds.has(entry.id)) errors.push(`${label}: duplicate id`);
    else seenIds.add(entry.id);

    const guarded = GUARDED_KINDS.has(entry.kind) || entry.preserve === true;
    if (guarded && entry.preserve !== true) errors.push(`${label}: guarded entries must set preserve:true`);
    if (guarded && Object.hasOwn(entry, "ko")) errors.push(`${label}: guarded entries must not define ko`);

    if (!Object.hasOwn(entry, "ko")) continue;
    if (guarded) continue;
    if (!TRANSLATED_KINDS.has(entry.kind)) {
      errors.push(`${label}: only fixed UI labels/formats/diagnostics may define ko`);
      continue;
    }
    if (typeof entry.ko !== "string" || entry.ko.length === 0) {
      errors.push(`${label}: ko must be a non-empty string`);
      continue;
    }

    stringEntries.push({ id: entry.id, source: entry.source ?? "", ko: entry.ko, kind: entry.kind });
    for (const char of entry.ko) {
      const codePoint = char.codePointAt(0);
      if (char === "\r" || char === "\n" || char === "\t") continue;
      if (codePoint > 0xFFFF || codePoint === 0xFE0E || codePoint === 0xFE0F) continue;
      glyphCodePoints.add(codePoint);
    }
  }

  return {
    errors,
    stringEntries,
    glyphChars: [...glyphCodePoints]
      .sort((a, b) => a - b)
      .map((codePoint) => String.fromCodePoint(codePoint))
      .filter((char) => char.length === 1),
  };
};

const pythonProbe = "from PIL import Image, ImageDraw, ImageFont\nprint('ok')";

const candidateKey = (candidate) => `${candidate.command}\u0000${candidate.args.join("\u0000")}`;

const commandExists = (command) => {
  const result = childProcess.spawnSync(command, ["--version"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    shell: false,
  });
  return result.error === undefined;
};

const splitLines = (value) => value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);

const whereCandidates = (command) => {
  if (process.platform !== "win32") return [];
  const result = childProcess.spawnSync("where", [command], { encoding: "utf8", shell: false });
  if (result.status !== 0) return [];
  return splitLines(result.stdout).map((line) => ({ command: line, args: [] }));
};

const pythonCandidates = () => {
  const candidates = [];
  if (process.env.PYTHON) candidates.push({ command: process.env.PYTHON, args: [] });
  candidates.push(...whereCandidates("python"));
  candidates.push(...whereCandidates("python3"));
  candidates.push(...whereCandidates("py").map((candidate) => ({ command: candidate.command, args: ["-3"] })));
  candidates.push({ command: "python3", args: [] });
  candidates.push({ command: "python", args: [] });
  if (process.platform === "win32") candidates.push({ command: "py", args: ["-3"] });

  const unique = new Map();
  for (const candidate of candidates) unique.set(candidateKey(candidate), candidate);
  return [...unique.values()].filter((candidate) => commandExists(candidate.command));
};

const findPython = () => {
  const errors = [];
  for (const candidate of pythonCandidates()) {
    const result = childProcess.spawnSync(candidate.command, [...candidate.args, "-c", pythonProbe], {
      encoding: "utf8",
      shell: false,
      stdio: ["ignore", "pipe", "pipe"],
      timeout: 10000,
    });
    if (result.status === 0 && result.stdout.includes("ok")) return candidate;
    errors.push(`${candidate.command} ${candidate.args.join(" ")}: ${(result.stderr || result.stdout || result.error?.message || "failed").trim()}`);
  }

  throw new Error(
    `Could not find Python with Pillow installed. Tried ${errors.length} candidate(s).\n${errors.join("\n")}`,
  );
};

const pythonRenderer = String.raw`
import json
import math
import sys
from PIL import Image, ImageDraw, ImageFont

request = json.load(sys.stdin)
font = ImageFont.truetype(request["fontPath"], request["pixelSize"])
ascent, descent = font.getmetrics()
line_height = int(ascent + descent)

def render_glyph(char, code_point):
    bbox = font.getbbox(char)
    advance = max(1, int(math.ceil(font.getlength(char))))
    if bbox is None:
        width = advance
        height = max(1, line_height)
        rows = ["0" * width for _ in range(height)]
        return {
            "char": char,
            "codePoint": code_point,
            "width": width,
            "height": height,
            "advance": advance,
            "xOffset": 0,
            "yOffset": 0,
            "pixels": rows,
        }

    left, top, right, bottom = bbox
    width = max(1, int(math.ceil(right - left)))
    height = max(1, int(math.ceil(bottom - top)))
    image = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(image)
    draw.text((-left, -top), char, font=font, fill=255)
    rows = []
    for y in range(height):
        row = []
        for x in range(width):
            row.append("1" if image.getpixel((x, y)) >= 32 else "0")
        rows.append("".join(row))
    return {
        "char": char,
        "codePoint": code_point,
        "width": width,
        "height": height,
        "advance": advance,
        "xOffset": int(left),
        "yOffset": int(top),
        "pixels": rows,
    }

glyphs = [render_glyph(chr(code_point), code_point) for code_point in request["codePoints"]]
json.dump({
    "pixelSize": request["pixelSize"],
    "lineHeight": line_height,
    "ascent": int(ascent),
    "descent": int(descent),
    "glyphs": glyphs,
}, sys.stdout, ensure_ascii=True, separators=(",", ":"))
`;

const renderGlyphs = (config, glyphChars) => {
  const python = findPython();
  const result = childProcess.spawnSync(python.command, [...python.args, "-c", pythonRenderer], {
    encoding: "utf8",
    input: JSON.stringify({
      fontPath: config.fontPath,
      pixelSize: config.pixelSize,
      codePoints: glyphChars.map((char) => char.codePointAt(0)),
    }),
    maxBuffer: 64 * 1024 * 1024,
    shell: false,
    timeout: 120000,
  });

  if (result.status !== 0) {
    throw new Error(`Python glyph renderer failed with ${python.command}: ${result.stderr || result.stdout}`);
  }

  const rendered = JSON.parse(result.stdout);
  return { ...rendered, renderer: `${python.command}${python.args.length ? ` ${python.args.join(" ")}` : ""}` };
};

const jsString = (value) => JSON.stringify(value);

const cString = (value) => {
  let escaped = "";
  for (const char of value) {
    if (char === "\\") escaped += "\\\\";
    else if (char === "\"") escaped += "\\\"";
    else if (char === "\n") escaped += "\\n";
    else if (char === "\r") escaped += "\\r";
    else if (char === "\t") escaped += "\\t";
    else escaped += char;
  }
  return `"${escaped}"`;
};

const hexCodePoint = (codePoint) => `0x${codePoint.toString(16).toUpperCase().padStart(4, "0")}`;

const buildSignature = ({ fontHash, inventoryHash, pixelSize, stringEntries, glyphChars }) => sha256(JSON.stringify({
  generator: "decker-ko-ui-assets-v1",
  fontHash,
  inventoryHash,
  pixelSize,
  stringIds: stringEntries.map((entry) => entry.id),
  glyphCodePoints: glyphChars.map((char) => char.codePointAt(0)),
}));

const generatedHeader = (signature, extra = "") => [
  `/* ${GENERATED_NOTICE}`,
  ` * source-hash: ${signature}`,
  extra ? ` * ${extra}` : undefined,
  " */",
  "",
].filter((line) => line !== undefined).join("\n");

const buildJsStrings = ({ signature, fontHash, inventoryHash, stringEntries }) => {
  const entries = stringEntries
    .map((entry) => `  ${jsString(entry.id)}: ${jsString(entry.ko)},`)
    .join("\n");
  const keys = stringEntries.map((entry) => jsString(entry.id)).join(", ");

  return `${generatedHeader(signature, `font-sha256: ${fontHash}; strings-sha256: ${inventoryHash}`)}const KO_UI_STRINGS_VERSION = ${jsString(signature)};
const KO_UI_STRINGS = Object.freeze({
${entries}
});
const KO_UI_STRING_IDS = Object.freeze([${keys}]);

globalThis.KO_UI_STRINGS_VERSION = KO_UI_STRINGS_VERSION;
globalThis.KO_UI_STRINGS = KO_UI_STRINGS;
globalThis.KO_UI_STRING_IDS = KO_UI_STRING_IDS;

if (typeof module !== "undefined" && module.exports) {
  module.exports = { KO_UI_STRINGS_VERSION, KO_UI_STRINGS, KO_UI_STRING_IDS };
}
`;
};

const buildJsFont = ({ signature, rendered }) => {
  const glyphLines = rendered.glyphs.map((glyph) => {
    const key = jsString(String(glyph.codePoint));
    const rows = glyph.pixels.map((row) => jsString(row)).join(", ");
    return `    ${key}: { codePoint: ${glyph.codePoint}, width: ${glyph.width}, height: ${glyph.height}, advance: ${glyph.advance}, xOffset: ${glyph.xOffset}, yOffset: ${glyph.yOffset}, pixels: Object.freeze([${rows}]) },`;
  }).join("\n");

  return `${generatedHeader(signature, `glyph-count: ${rendered.glyphs.length}; renderer: ${rendered.renderer}`)}const KO_UI_FONT_VERSION = ${jsString(signature)};
const KO_UI_FONT = Object.freeze({
  version: KO_UI_FONT_VERSION,
  pixelSize: ${rendered.pixelSize},
  lineHeight: ${rendered.lineHeight},
  ascent: ${rendered.ascent},
  descent: ${rendered.descent},
  glyphs: Object.freeze({
${glyphLines}
  }),
});

globalThis.KO_UI_FONT_VERSION = KO_UI_FONT_VERSION;
globalThis.KO_UI_FONT = KO_UI_FONT;

if (typeof module !== "undefined" && module.exports) {
  module.exports = { KO_UI_FONT_VERSION, KO_UI_FONT };
}
`;
};

const buildCStringHeader = ({ signature, stringEntries }) => {
  const rows = stringEntries
    .map((entry) => `  { ${cString(entry.id)}, ${cString(entry.ko)} },`)
    .join("\n");

  return `${generatedHeader(signature)}#ifndef DECKER_KO_UI_STRINGS_H
#define DECKER_KO_UI_STRINGS_H

#define KO_UI_STRINGS_VERSION ${cString(signature)}
#define KO_UI_STRING_COUNT ${stringEntries.length}

typedef struct {
  const char *id;
  const char *text;
} ko_ui_string_t;

static const ko_ui_string_t KO_UI_STRINGS[KO_UI_STRING_COUNT] = {
${rows}
};

#endif
`;
};

const buildCFontHeader = ({ signature, rendered }) => {
  const maxHeight = Math.max(...rendered.glyphs.map((glyph) => glyph.height), 1);
  const rows = rendered.glyphs.map((glyph) => {
    const pixelRows = glyph.pixels.map((row) => cString(row)).join(", ");
    return `  { ${hexCodePoint(glyph.codePoint)}, ${glyph.width}, ${glyph.height}, ${glyph.advance}, ${glyph.xOffset}, ${glyph.yOffset}, { ${pixelRows} } },`;
  }).join("\n");

  return `${generatedHeader(signature, `glyph-count: ${rendered.glyphs.length}; renderer: ${rendered.renderer}`)}#ifndef DECKER_KO_UI_FONT_H
#define DECKER_KO_UI_FONT_H

#define KO_UI_FONT 1
#define KO_UI_FONT_VERSION ${cString(signature)}
#define KO_UI_FONT_PIXEL_SIZE ${rendered.pixelSize}
#define KO_UI_FONT_LINE_HEIGHT ${rendered.lineHeight}
#define KO_UI_FONT_ASCENT ${rendered.ascent}
#define KO_UI_FONT_DESCENT ${rendered.descent}
#define KO_UI_GLYPH_COUNT ${rendered.glyphs.length}
#define KO_UI_FONT_MAX_HEIGHT ${maxHeight}

typedef struct {
  unsigned int codepoint;
  unsigned char width;
  unsigned char height;
  unsigned char advance;
  signed char x_offset;
  signed char y_offset;
  const char *rows[KO_UI_FONT_MAX_HEIGHT];
} ko_ui_glyph_t;

static const ko_ui_glyph_t KO_UI_GLYPHS[KO_UI_GLYPH_COUNT] = {
${rows}
};

#endif
`;
};

const outputPaths = (outRoot) => ({
  jsStrings: path.join(outRoot, "js", "ko-ui-strings.js"),
  jsFont: path.join(outRoot, "js", "ko-ui-font.js"),
  cStrings: path.join(outRoot, "c", "ko_ui_strings.h"),
  cFont: path.join(outRoot, "c", "ko_ui_font.h"),
});

const buildAssets = (config) => {
  if (!fs.existsSync(config.fontPath)) throw new Error(`Font not found: ${config.fontPath}`);
  if (!fs.existsSync(config.stringsPath)) throw new Error(`String inventory not found: ${config.stringsPath}`);

  const inventoryText = fs.readFileSync(config.stringsPath, "utf8");
  const inventory = JSON.parse(inventoryText);
  const { errors, stringEntries, glyphChars } = validateInventory(inventory);
  if (errors.length > 0) throw new Error(`Korean UI inventory validation failed:\n- ${errors.join("\n- ")}`);
  if (stringEntries.length === 0) throw new Error("No Korean fixed UI strings found in inventory");
  if (glyphChars.length === 0) throw new Error("No glyphs required by Korean fixed UI strings");

  const fontHash = sha256File(config.fontPath);
  const inventoryHash = sha256(inventoryText);
  const signature = buildSignature({ fontHash, inventoryHash, pixelSize: config.pixelSize, stringEntries, glyphChars });
  const rendered = renderGlyphs(config, glyphChars);

  return {
    signature,
    fontHash,
    inventoryHash,
    glyphCount: rendered.glyphs.length,
    stringCount: stringEntries.length,
    renderer: rendered.renderer,
    files: new Map([
      ["jsStrings", buildJsStrings({ signature, fontHash, inventoryHash, stringEntries })],
      ["jsFont", buildJsFont({ signature, rendered })],
      ["cStrings", buildCStringHeader({ signature, stringEntries })],
      ["cFont", buildCFontHeader({ signature, rendered })],
    ]),
  };
};

const writeAssets = (paths, assets) => {
  for (const [key, content] of assets.files.entries()) {
    fs.mkdirSync(path.dirname(paths[key]), { recursive: true });
    fs.writeFileSync(paths[key], content, "utf8");
  }
};

const checkAssets = (paths, assets) => {
  const mismatches = [];
  for (const [key, expected] of assets.files.entries()) {
    const filePath = paths[key];
    if (!fs.existsSync(filePath)) {
      mismatches.push(`missing ${slash(filePath)}`);
      continue;
    }
    const actual = fs.readFileSync(filePath, "utf8");
    if (actual !== expected) mismatches.push(`stale ${slash(filePath)}`);
  }
  return mismatches;
};

const main = () => {
  const config = parseArgs(process.argv.slice(2));
  if (config.help) {
    console.log(usage());
    return;
  }

  const paths = outputPaths(config.outRoot);
  const assets = buildAssets(config);

  if (config.check) {
    const mismatches = checkAssets(paths, assets);
    if (mismatches.length > 0) {
      console.error("Korean UI generated assets are stale");
      for (const mismatch of mismatches) console.error(`- ${mismatch}`);
      process.exit(1);
    }
    console.log("OK Korean UI generated assets are current");
  } else {
    writeAssets(paths, assets);
    console.log("Generated Korean UI assets");
  }

  console.log(`source hash: ${assets.signature}`);
  console.log(`strings: ${assets.stringCount}`);
  console.log(`glyphs: ${assets.glyphCount}`);
  console.log(`renderer: ${assets.renderer}`);
  console.log(`outputs: ${Object.values(paths).map((filePath) => slash(filePath)).join(", ")}`);
};

try {
  main();
} catch (error) {
  if (error instanceof UsageError) console.error(usage());
  console.error(error.message);
  process.exit(1);
}
